name: Deploy Lambda as Docker

on:
  push:
    branches:
      - main  # Runs when you push to the main branch
  workflow_dispatch:  # Allows manual trigger in GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your AWS region

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/lambda-docker-repo:latest .

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/lambda-docker-repo:latest

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code --function-name my-lambda-docker \
            --image-uri ${{ secrets.ECR_REGISTRY }}/lambda-docker-repo:latest
